// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.stock.proto;

public interface RequestWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.stock.RequestWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.stock.UpsertStockRequest upsert_stock_request = 1;</code>
   * @return Whether the upsertStockRequest field is set.
   */
  boolean hasUpsertStockRequest();
  /**
   * <code>.com.example.demo.stock.UpsertStockRequest upsert_stock_request = 1;</code>
   * @return The upsertStockRequest.
   */
  com.example.demo.stock.proto.UpsertStockRequest getUpsertStockRequest();
  /**
   * <code>.com.example.demo.stock.UpsertStockRequest upsert_stock_request = 1;</code>
   */
  com.example.demo.stock.proto.UpsertStockRequestOrBuilder getUpsertStockRequestOrBuilder();

  /**
   * <code>.com.example.demo.stock.ReserveOrderRequest reserve_order_request = 2;</code>
   * @return Whether the reserveOrderRequest field is set.
   */
  boolean hasReserveOrderRequest();
  /**
   * <code>.com.example.demo.stock.ReserveOrderRequest reserve_order_request = 2;</code>
   * @return The reserveOrderRequest.
   */
  com.example.demo.stock.proto.ReserveOrderRequest getReserveOrderRequest();
  /**
   * <code>.com.example.demo.stock.ReserveOrderRequest reserve_order_request = 2;</code>
   */
  com.example.demo.stock.proto.ReserveOrderRequestOrBuilder getReserveOrderRequestOrBuilder();

  com.example.demo.stock.proto.RequestWrapper.RequestCase getRequestCase();
}
