// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.stock.proto;

public interface ReserveOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.stock.ReserveOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  java.util.List<com.example.demo.stock.proto.StockMessage> 
      getStocksList();
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  com.example.demo.stock.proto.StockMessage getStocks(int index);
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  int getStocksCount();
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  java.util.List<? extends com.example.demo.stock.proto.StockMessageOrBuilder> 
      getStocksOrBuilderList();
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  com.example.demo.stock.proto.StockMessageOrBuilder getStocksOrBuilder(
      int index);
}
