// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.stock.proto;

public interface ReserveOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.stock.ReserveOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.demo.stock.ReserveItem items = 1;</code>
   */
  java.util.List<com.example.demo.stock.proto.ReserveItem> 
      getItemsList();
  /**
   * <code>repeated .com.example.demo.stock.ReserveItem items = 1;</code>
   */
  com.example.demo.stock.proto.ReserveItem getItems(int index);
  /**
   * <code>repeated .com.example.demo.stock.ReserveItem items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.example.demo.stock.ReserveItem items = 1;</code>
   */
  java.util.List<? extends com.example.demo.stock.proto.ReserveItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.example.demo.stock.ReserveItem items = 1;</code>
   */
  com.example.demo.stock.proto.ReserveItemOrBuilder getItemsOrBuilder(
      int index);
}
