// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.stock.proto;

/**
 * Protobuf type {@code com.example.demo.stock.ReserveOrderResponse}
 */
public final class ReserveOrderResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.stock.ReserveOrderResponse)
    ReserveOrderResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ReserveOrderResponse.class.getName());
  }
  // Use ReserveOrderResponse.newBuilder() to construct.
  private ReserveOrderResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ReserveOrderResponse() {
    stocks_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ReserveOrderResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ReserveOrderResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.stock.proto.ReserveOrderResponse.class, com.example.demo.stock.proto.ReserveOrderResponse.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int STOCKS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.example.demo.stock.proto.StockMessage> stocks_;
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.demo.stock.proto.StockMessage> getStocksList() {
    return stocks_;
  }
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.demo.stock.proto.StockMessageOrBuilder> 
      getStocksOrBuilderList() {
    return stocks_;
  }
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  @java.lang.Override
  public int getStocksCount() {
    return stocks_.size();
  }
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  @java.lang.Override
  public com.example.demo.stock.proto.StockMessage getStocks(int index) {
    return stocks_.get(index);
  }
  /**
   * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
   */
  @java.lang.Override
  public com.example.demo.stock.proto.StockMessageOrBuilder getStocksOrBuilder(
      int index) {
    return stocks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    for (int i = 0; i < stocks_.size(); i++) {
      output.writeMessage(2, stocks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    for (int i = 0; i < stocks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, stocks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.stock.proto.ReserveOrderResponse)) {
      return super.equals(obj);
    }
    com.example.demo.stock.proto.ReserveOrderResponse other = (com.example.demo.stock.proto.ReserveOrderResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getStocksList()
        .equals(other.getStocksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (getStocksCount() > 0) {
      hash = (37 * hash) + STOCKS_FIELD_NUMBER;
      hash = (53 * hash) + getStocksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.stock.proto.ReserveOrderResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.stock.proto.ReserveOrderResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.stock.proto.ReserveOrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.stock.proto.ReserveOrderResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.stock.ReserveOrderResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.stock.ReserveOrderResponse)
      com.example.demo.stock.proto.ReserveOrderResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ReserveOrderResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ReserveOrderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.stock.proto.ReserveOrderResponse.class, com.example.demo.stock.proto.ReserveOrderResponse.Builder.class);
    }

    // Construct using com.example.demo.stock.proto.ReserveOrderResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      if (stocksBuilder_ == null) {
        stocks_ = java.util.Collections.emptyList();
      } else {
        stocks_ = null;
        stocksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ReserveOrderResponse_descriptor;
    }

    @java.lang.Override
    public com.example.demo.stock.proto.ReserveOrderResponse getDefaultInstanceForType() {
      return com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.stock.proto.ReserveOrderResponse build() {
      com.example.demo.stock.proto.ReserveOrderResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.stock.proto.ReserveOrderResponse buildPartial() {
      com.example.demo.stock.proto.ReserveOrderResponse result = new com.example.demo.stock.proto.ReserveOrderResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.demo.stock.proto.ReserveOrderResponse result) {
      if (stocksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          stocks_ = java.util.Collections.unmodifiableList(stocks_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.stocks_ = stocks_;
      } else {
        result.stocks_ = stocksBuilder_.build();
      }
    }

    private void buildPartial0(com.example.demo.stock.proto.ReserveOrderResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.stock.proto.ReserveOrderResponse) {
        return mergeFrom((com.example.demo.stock.proto.ReserveOrderResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.stock.proto.ReserveOrderResponse other) {
      if (other == com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (stocksBuilder_ == null) {
        if (!other.stocks_.isEmpty()) {
          if (stocks_.isEmpty()) {
            stocks_ = other.stocks_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStocksIsMutable();
            stocks_.addAll(other.stocks_);
          }
          onChanged();
        }
      } else {
        if (!other.stocks_.isEmpty()) {
          if (stocksBuilder_.isEmpty()) {
            stocksBuilder_.dispose();
            stocksBuilder_ = null;
            stocks_ = other.stocks_;
            bitField0_ = (bitField0_ & ~0x00000002);
            stocksBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getStocksFieldBuilder() : null;
          } else {
            stocksBuilder_.addAllMessages(other.stocks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.example.demo.stock.proto.StockMessage m =
                  input.readMessage(
                      com.example.demo.stock.proto.StockMessage.parser(),
                      extensionRegistry);
              if (stocksBuilder_ == null) {
                ensureStocksIsMutable();
                stocks_.add(m);
              } else {
                stocksBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.example.demo.stock.proto.StockMessage> stocks_ =
      java.util.Collections.emptyList();
    private void ensureStocksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        stocks_ = new java.util.ArrayList<com.example.demo.stock.proto.StockMessage>(stocks_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.demo.stock.proto.StockMessage, com.example.demo.stock.proto.StockMessage.Builder, com.example.demo.stock.proto.StockMessageOrBuilder> stocksBuilder_;

    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public java.util.List<com.example.demo.stock.proto.StockMessage> getStocksList() {
      if (stocksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stocks_);
      } else {
        return stocksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public int getStocksCount() {
      if (stocksBuilder_ == null) {
        return stocks_.size();
      } else {
        return stocksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public com.example.demo.stock.proto.StockMessage getStocks(int index) {
      if (stocksBuilder_ == null) {
        return stocks_.get(index);
      } else {
        return stocksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder setStocks(
        int index, com.example.demo.stock.proto.StockMessage value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.set(index, value);
        onChanged();
      } else {
        stocksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder setStocks(
        int index, com.example.demo.stock.proto.StockMessage.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.set(index, builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder addStocks(com.example.demo.stock.proto.StockMessage value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.add(value);
        onChanged();
      } else {
        stocksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder addStocks(
        int index, com.example.demo.stock.proto.StockMessage value) {
      if (stocksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStocksIsMutable();
        stocks_.add(index, value);
        onChanged();
      } else {
        stocksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder addStocks(
        com.example.demo.stock.proto.StockMessage.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.add(builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder addStocks(
        int index, com.example.demo.stock.proto.StockMessage.Builder builderForValue) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.add(index, builderForValue.build());
        onChanged();
      } else {
        stocksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder addAllStocks(
        java.lang.Iterable<? extends com.example.demo.stock.proto.StockMessage> values) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stocks_);
        onChanged();
      } else {
        stocksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder clearStocks() {
      if (stocksBuilder_ == null) {
        stocks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        stocksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public Builder removeStocks(int index) {
      if (stocksBuilder_ == null) {
        ensureStocksIsMutable();
        stocks_.remove(index);
        onChanged();
      } else {
        stocksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public com.example.demo.stock.proto.StockMessage.Builder getStocksBuilder(
        int index) {
      return getStocksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public com.example.demo.stock.proto.StockMessageOrBuilder getStocksOrBuilder(
        int index) {
      if (stocksBuilder_ == null) {
        return stocks_.get(index);  } else {
        return stocksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public java.util.List<? extends com.example.demo.stock.proto.StockMessageOrBuilder> 
         getStocksOrBuilderList() {
      if (stocksBuilder_ != null) {
        return stocksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stocks_);
      }
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public com.example.demo.stock.proto.StockMessage.Builder addStocksBuilder() {
      return getStocksFieldBuilder().addBuilder(
          com.example.demo.stock.proto.StockMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public com.example.demo.stock.proto.StockMessage.Builder addStocksBuilder(
        int index) {
      return getStocksFieldBuilder().addBuilder(
          index, com.example.demo.stock.proto.StockMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.demo.stock.StockMessage stocks = 2;</code>
     */
    public java.util.List<com.example.demo.stock.proto.StockMessage.Builder> 
         getStocksBuilderList() {
      return getStocksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.demo.stock.proto.StockMessage, com.example.demo.stock.proto.StockMessage.Builder, com.example.demo.stock.proto.StockMessageOrBuilder> 
        getStocksFieldBuilder() {
      if (stocksBuilder_ == null) {
        stocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.example.demo.stock.proto.StockMessage, com.example.demo.stock.proto.StockMessage.Builder, com.example.demo.stock.proto.StockMessageOrBuilder>(
                stocks_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        stocks_ = null;
      }
      return stocksBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.stock.ReserveOrderResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.stock.ReserveOrderResponse)
  private static final com.example.demo.stock.proto.ReserveOrderResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.stock.proto.ReserveOrderResponse();
  }

  public static com.example.demo.stock.proto.ReserveOrderResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReserveOrderResponse>
      PARSER = new com.google.protobuf.AbstractParser<ReserveOrderResponse>() {
    @java.lang.Override
    public ReserveOrderResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ReserveOrderResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReserveOrderResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.stock.proto.ReserveOrderResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

