// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.stock.proto;

public interface ResponseWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.stock.ResponseWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
   * @return Whether the upsertStockResponse field is set.
   */
  boolean hasUpsertStockResponse();
  /**
   * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
   * @return The upsertStockResponse.
   */
  com.example.demo.stock.proto.StockMessage getUpsertStockResponse();
  /**
   * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
   */
  com.example.demo.stock.proto.StockMessageOrBuilder getUpsertStockResponseOrBuilder();

  /**
   * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
   * @return Whether the reserveOrderResponse field is set.
   */
  boolean hasReserveOrderResponse();
  /**
   * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
   * @return The reserveOrderResponse.
   */
  com.example.demo.stock.proto.ReserveOrderResponse getReserveOrderResponse();
  /**
   * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
   */
  com.example.demo.stock.proto.ReserveOrderResponseOrBuilder getReserveOrderResponseOrBuilder();

  com.example.demo.stock.proto.ResponseWrapper.ResponseCase getResponseCase();
}
