// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.stock.proto;

/**
 * Protobuf type {@code com.example.demo.stock.ResponseWrapper}
 */
public final class ResponseWrapper extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.stock.ResponseWrapper)
    ResponseWrapperOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ResponseWrapper.class.getName());
  }
  // Use ResponseWrapper.newBuilder() to construct.
  private ResponseWrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResponseWrapper() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ResponseWrapper_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ResponseWrapper_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.stock.proto.ResponseWrapper.class, com.example.demo.stock.proto.ResponseWrapper.Builder.class);
  }

  private int responseCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object response_;
  public enum ResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UPSERT_STOCK_RESPONSE(1),
    RESERVE_ORDER_RESPONSE(2),
    RESPONSE_NOT_SET(0);
    private final int value;
    private ResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCase forNumber(int value) {
      switch (value) {
        case 1: return UPSERT_STOCK_RESPONSE;
        case 2: return RESERVE_ORDER_RESPONSE;
        case 0: return RESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResponseCase
  getResponseCase() {
    return ResponseCase.forNumber(
        responseCase_);
  }

  public static final int UPSERT_STOCK_RESPONSE_FIELD_NUMBER = 1;
  /**
   * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
   * @return Whether the upsertStockResponse field is set.
   */
  @java.lang.Override
  public boolean hasUpsertStockResponse() {
    return responseCase_ == 1;
  }
  /**
   * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
   * @return The upsertStockResponse.
   */
  @java.lang.Override
  public com.example.demo.stock.proto.StockMessage getUpsertStockResponse() {
    if (responseCase_ == 1) {
       return (com.example.demo.stock.proto.StockMessage) response_;
    }
    return com.example.demo.stock.proto.StockMessage.getDefaultInstance();
  }
  /**
   * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
   */
  @java.lang.Override
  public com.example.demo.stock.proto.StockMessageOrBuilder getUpsertStockResponseOrBuilder() {
    if (responseCase_ == 1) {
       return (com.example.demo.stock.proto.StockMessage) response_;
    }
    return com.example.demo.stock.proto.StockMessage.getDefaultInstance();
  }

  public static final int RESERVE_ORDER_RESPONSE_FIELD_NUMBER = 2;
  /**
   * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
   * @return Whether the reserveOrderResponse field is set.
   */
  @java.lang.Override
  public boolean hasReserveOrderResponse() {
    return responseCase_ == 2;
  }
  /**
   * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
   * @return The reserveOrderResponse.
   */
  @java.lang.Override
  public com.example.demo.stock.proto.ReserveOrderResponse getReserveOrderResponse() {
    if (responseCase_ == 2) {
       return (com.example.demo.stock.proto.ReserveOrderResponse) response_;
    }
    return com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance();
  }
  /**
   * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
   */
  @java.lang.Override
  public com.example.demo.stock.proto.ReserveOrderResponseOrBuilder getReserveOrderResponseOrBuilder() {
    if (responseCase_ == 2) {
       return (com.example.demo.stock.proto.ReserveOrderResponse) response_;
    }
    return com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (responseCase_ == 1) {
      output.writeMessage(1, (com.example.demo.stock.proto.StockMessage) response_);
    }
    if (responseCase_ == 2) {
      output.writeMessage(2, (com.example.demo.stock.proto.ReserveOrderResponse) response_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (responseCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.example.demo.stock.proto.StockMessage) response_);
    }
    if (responseCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.example.demo.stock.proto.ReserveOrderResponse) response_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.stock.proto.ResponseWrapper)) {
      return super.equals(obj);
    }
    com.example.demo.stock.proto.ResponseWrapper other = (com.example.demo.stock.proto.ResponseWrapper) obj;

    if (!getResponseCase().equals(other.getResponseCase())) return false;
    switch (responseCase_) {
      case 1:
        if (!getUpsertStockResponse()
            .equals(other.getUpsertStockResponse())) return false;
        break;
      case 2:
        if (!getReserveOrderResponse()
            .equals(other.getReserveOrderResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (responseCase_) {
      case 1:
        hash = (37 * hash) + UPSERT_STOCK_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getUpsertStockResponse().hashCode();
        break;
      case 2:
        hash = (37 * hash) + RESERVE_ORDER_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getReserveOrderResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.stock.proto.ResponseWrapper parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.stock.proto.ResponseWrapper parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.stock.proto.ResponseWrapper parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.stock.proto.ResponseWrapper prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.stock.ResponseWrapper}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.stock.ResponseWrapper)
      com.example.demo.stock.proto.ResponseWrapperOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ResponseWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ResponseWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.stock.proto.ResponseWrapper.class, com.example.demo.stock.proto.ResponseWrapper.Builder.class);
    }

    // Construct using com.example.demo.stock.proto.ResponseWrapper.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (upsertStockResponseBuilder_ != null) {
        upsertStockResponseBuilder_.clear();
      }
      if (reserveOrderResponseBuilder_ != null) {
        reserveOrderResponseBuilder_.clear();
      }
      responseCase_ = 0;
      response_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_ResponseWrapper_descriptor;
    }

    @java.lang.Override
    public com.example.demo.stock.proto.ResponseWrapper getDefaultInstanceForType() {
      return com.example.demo.stock.proto.ResponseWrapper.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.stock.proto.ResponseWrapper build() {
      com.example.demo.stock.proto.ResponseWrapper result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.stock.proto.ResponseWrapper buildPartial() {
      com.example.demo.stock.proto.ResponseWrapper result = new com.example.demo.stock.proto.ResponseWrapper(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.demo.stock.proto.ResponseWrapper result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.example.demo.stock.proto.ResponseWrapper result) {
      result.responseCase_ = responseCase_;
      result.response_ = this.response_;
      if (responseCase_ == 1 &&
          upsertStockResponseBuilder_ != null) {
        result.response_ = upsertStockResponseBuilder_.build();
      }
      if (responseCase_ == 2 &&
          reserveOrderResponseBuilder_ != null) {
        result.response_ = reserveOrderResponseBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.stock.proto.ResponseWrapper) {
        return mergeFrom((com.example.demo.stock.proto.ResponseWrapper)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.stock.proto.ResponseWrapper other) {
      if (other == com.example.demo.stock.proto.ResponseWrapper.getDefaultInstance()) return this;
      switch (other.getResponseCase()) {
        case UPSERT_STOCK_RESPONSE: {
          mergeUpsertStockResponse(other.getUpsertStockResponse());
          break;
        }
        case RESERVE_ORDER_RESPONSE: {
          mergeReserveOrderResponse(other.getReserveOrderResponse());
          break;
        }
        case RESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUpsertStockResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              responseCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getReserveOrderResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              responseCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int responseCase_ = 0;
    private java.lang.Object response_;
    public ResponseCase
        getResponseCase() {
      return ResponseCase.forNumber(
          responseCase_);
    }

    public Builder clearResponse() {
      responseCase_ = 0;
      response_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.example.demo.stock.proto.StockMessage, com.example.demo.stock.proto.StockMessage.Builder, com.example.demo.stock.proto.StockMessageOrBuilder> upsertStockResponseBuilder_;
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     * @return Whether the upsertStockResponse field is set.
     */
    @java.lang.Override
    public boolean hasUpsertStockResponse() {
      return responseCase_ == 1;
    }
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     * @return The upsertStockResponse.
     */
    @java.lang.Override
    public com.example.demo.stock.proto.StockMessage getUpsertStockResponse() {
      if (upsertStockResponseBuilder_ == null) {
        if (responseCase_ == 1) {
          return (com.example.demo.stock.proto.StockMessage) response_;
        }
        return com.example.demo.stock.proto.StockMessage.getDefaultInstance();
      } else {
        if (responseCase_ == 1) {
          return upsertStockResponseBuilder_.getMessage();
        }
        return com.example.demo.stock.proto.StockMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     */
    public Builder setUpsertStockResponse(com.example.demo.stock.proto.StockMessage value) {
      if (upsertStockResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        upsertStockResponseBuilder_.setMessage(value);
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     */
    public Builder setUpsertStockResponse(
        com.example.demo.stock.proto.StockMessage.Builder builderForValue) {
      if (upsertStockResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        upsertStockResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     */
    public Builder mergeUpsertStockResponse(com.example.demo.stock.proto.StockMessage value) {
      if (upsertStockResponseBuilder_ == null) {
        if (responseCase_ == 1 &&
            response_ != com.example.demo.stock.proto.StockMessage.getDefaultInstance()) {
          response_ = com.example.demo.stock.proto.StockMessage.newBuilder((com.example.demo.stock.proto.StockMessage) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 1) {
          upsertStockResponseBuilder_.mergeFrom(value);
        } else {
          upsertStockResponseBuilder_.setMessage(value);
        }
      }
      responseCase_ = 1;
      return this;
    }
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     */
    public Builder clearUpsertStockResponse() {
      if (upsertStockResponseBuilder_ == null) {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 1) {
          responseCase_ = 0;
          response_ = null;
        }
        upsertStockResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     */
    public com.example.demo.stock.proto.StockMessage.Builder getUpsertStockResponseBuilder() {
      return getUpsertStockResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     */
    @java.lang.Override
    public com.example.demo.stock.proto.StockMessageOrBuilder getUpsertStockResponseOrBuilder() {
      if ((responseCase_ == 1) && (upsertStockResponseBuilder_ != null)) {
        return upsertStockResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 1) {
          return (com.example.demo.stock.proto.StockMessage) response_;
        }
        return com.example.demo.stock.proto.StockMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.example.demo.stock.StockMessage upsert_stock_response = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.demo.stock.proto.StockMessage, com.example.demo.stock.proto.StockMessage.Builder, com.example.demo.stock.proto.StockMessageOrBuilder> 
        getUpsertStockResponseFieldBuilder() {
      if (upsertStockResponseBuilder_ == null) {
        if (!(responseCase_ == 1)) {
          response_ = com.example.demo.stock.proto.StockMessage.getDefaultInstance();
        }
        upsertStockResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.demo.stock.proto.StockMessage, com.example.demo.stock.proto.StockMessage.Builder, com.example.demo.stock.proto.StockMessageOrBuilder>(
                (com.example.demo.stock.proto.StockMessage) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 1;
      onChanged();
      return upsertStockResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.example.demo.stock.proto.ReserveOrderResponse, com.example.demo.stock.proto.ReserveOrderResponse.Builder, com.example.demo.stock.proto.ReserveOrderResponseOrBuilder> reserveOrderResponseBuilder_;
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     * @return Whether the reserveOrderResponse field is set.
     */
    @java.lang.Override
    public boolean hasReserveOrderResponse() {
      return responseCase_ == 2;
    }
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     * @return The reserveOrderResponse.
     */
    @java.lang.Override
    public com.example.demo.stock.proto.ReserveOrderResponse getReserveOrderResponse() {
      if (reserveOrderResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          return (com.example.demo.stock.proto.ReserveOrderResponse) response_;
        }
        return com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance();
      } else {
        if (responseCase_ == 2) {
          return reserveOrderResponseBuilder_.getMessage();
        }
        return com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     */
    public Builder setReserveOrderResponse(com.example.demo.stock.proto.ReserveOrderResponse value) {
      if (reserveOrderResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        response_ = value;
        onChanged();
      } else {
        reserveOrderResponseBuilder_.setMessage(value);
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     */
    public Builder setReserveOrderResponse(
        com.example.demo.stock.proto.ReserveOrderResponse.Builder builderForValue) {
      if (reserveOrderResponseBuilder_ == null) {
        response_ = builderForValue.build();
        onChanged();
      } else {
        reserveOrderResponseBuilder_.setMessage(builderForValue.build());
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     */
    public Builder mergeReserveOrderResponse(com.example.demo.stock.proto.ReserveOrderResponse value) {
      if (reserveOrderResponseBuilder_ == null) {
        if (responseCase_ == 2 &&
            response_ != com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance()) {
          response_ = com.example.demo.stock.proto.ReserveOrderResponse.newBuilder((com.example.demo.stock.proto.ReserveOrderResponse) response_)
              .mergeFrom(value).buildPartial();
        } else {
          response_ = value;
        }
        onChanged();
      } else {
        if (responseCase_ == 2) {
          reserveOrderResponseBuilder_.mergeFrom(value);
        } else {
          reserveOrderResponseBuilder_.setMessage(value);
        }
      }
      responseCase_ = 2;
      return this;
    }
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     */
    public Builder clearReserveOrderResponse() {
      if (reserveOrderResponseBuilder_ == null) {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
          onChanged();
        }
      } else {
        if (responseCase_ == 2) {
          responseCase_ = 0;
          response_ = null;
        }
        reserveOrderResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     */
    public com.example.demo.stock.proto.ReserveOrderResponse.Builder getReserveOrderResponseBuilder() {
      return getReserveOrderResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     */
    @java.lang.Override
    public com.example.demo.stock.proto.ReserveOrderResponseOrBuilder getReserveOrderResponseOrBuilder() {
      if ((responseCase_ == 2) && (reserveOrderResponseBuilder_ != null)) {
        return reserveOrderResponseBuilder_.getMessageOrBuilder();
      } else {
        if (responseCase_ == 2) {
          return (com.example.demo.stock.proto.ReserveOrderResponse) response_;
        }
        return com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.com.example.demo.stock.ReserveOrderResponse reserve_order_response = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.demo.stock.proto.ReserveOrderResponse, com.example.demo.stock.proto.ReserveOrderResponse.Builder, com.example.demo.stock.proto.ReserveOrderResponseOrBuilder> 
        getReserveOrderResponseFieldBuilder() {
      if (reserveOrderResponseBuilder_ == null) {
        if (!(responseCase_ == 2)) {
          response_ = com.example.demo.stock.proto.ReserveOrderResponse.getDefaultInstance();
        }
        reserveOrderResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.demo.stock.proto.ReserveOrderResponse, com.example.demo.stock.proto.ReserveOrderResponse.Builder, com.example.demo.stock.proto.ReserveOrderResponseOrBuilder>(
                (com.example.demo.stock.proto.ReserveOrderResponse) response_,
                getParentForChildren(),
                isClean());
        response_ = null;
      }
      responseCase_ = 2;
      onChanged();
      return reserveOrderResponseBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.stock.ResponseWrapper)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.stock.ResponseWrapper)
  private static final com.example.demo.stock.proto.ResponseWrapper DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.stock.proto.ResponseWrapper();
  }

  public static com.example.demo.stock.proto.ResponseWrapper getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseWrapper>
      PARSER = new com.google.protobuf.AbstractParser<ResponseWrapper>() {
    @java.lang.Override
    public ResponseWrapper parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResponseWrapper> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseWrapper> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.stock.proto.ResponseWrapper getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

