// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.stock.proto;

/**
 * Protobuf type {@code com.example.demo.stock.StockMessage}
 */
public final class StockMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.stock.StockMessage)
    StockMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      StockMessage.class.getName());
  }
  // Use StockMessage.newBuilder() to construct.
  private StockMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StockMessage() {
    countryCode_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_StockMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_StockMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.stock.proto.StockMessage.class, com.example.demo.stock.proto.StockMessage.Builder.class);
  }

  public static final int PRODUCT_ID_FIELD_NUMBER = 1;
  private long productId_ = 0L;
  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  @java.lang.Override
  public long getProductId() {
    return productId_;
  }

  public static final int COUNTRY_CODE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object countryCode_ = "";
  /**
   * <code>string country_code = 2;</code>
   * @return The countryCode.
   */
  @java.lang.Override
  public java.lang.String getCountryCode() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      countryCode_ = s;
      return s;
    }
  }
  /**
   * <code>string country_code = 2;</code>
   * @return The bytes for countryCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountryCodeBytes() {
    java.lang.Object ref = countryCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      countryCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVAILABLE_STOCK_FIELD_NUMBER = 3;
  private long availableStock_ = 0L;
  /**
   * <code>int64 available_stock = 3;</code>
   * @return The availableStock.
   */
  @java.lang.Override
  public long getAvailableStock() {
    return availableStock_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (productId_ != 0L) {
      output.writeInt64(1, productId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(countryCode_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, countryCode_);
    }
    if (availableStock_ != 0L) {
      output.writeInt64(3, availableStock_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (productId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, productId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(countryCode_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, countryCode_);
    }
    if (availableStock_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, availableStock_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.stock.proto.StockMessage)) {
      return super.equals(obj);
    }
    com.example.demo.stock.proto.StockMessage other = (com.example.demo.stock.proto.StockMessage) obj;

    if (getProductId()
        != other.getProductId()) return false;
    if (!getCountryCode()
        .equals(other.getCountryCode())) return false;
    if (getAvailableStock()
        != other.getAvailableStock()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProductId());
    hash = (37 * hash) + COUNTRY_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCountryCode().hashCode();
    hash = (37 * hash) + AVAILABLE_STOCK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAvailableStock());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.stock.proto.StockMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.stock.proto.StockMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.stock.proto.StockMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.stock.proto.StockMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.stock.proto.StockMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.stock.StockMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.stock.StockMessage)
      com.example.demo.stock.proto.StockMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_StockMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_StockMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.stock.proto.StockMessage.class, com.example.demo.stock.proto.StockMessage.Builder.class);
    }

    // Construct using com.example.demo.stock.proto.StockMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      productId_ = 0L;
      countryCode_ = "";
      availableStock_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.stock.proto.Messages.internal_static_com_example_demo_stock_StockMessage_descriptor;
    }

    @java.lang.Override
    public com.example.demo.stock.proto.StockMessage getDefaultInstanceForType() {
      return com.example.demo.stock.proto.StockMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.stock.proto.StockMessage build() {
      com.example.demo.stock.proto.StockMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.stock.proto.StockMessage buildPartial() {
      com.example.demo.stock.proto.StockMessage result = new com.example.demo.stock.proto.StockMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.demo.stock.proto.StockMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.productId_ = productId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.countryCode_ = countryCode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.availableStock_ = availableStock_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.stock.proto.StockMessage) {
        return mergeFrom((com.example.demo.stock.proto.StockMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.stock.proto.StockMessage other) {
      if (other == com.example.demo.stock.proto.StockMessage.getDefaultInstance()) return this;
      if (other.getProductId() != 0L) {
        setProductId(other.getProductId());
      }
      if (!other.getCountryCode().isEmpty()) {
        countryCode_ = other.countryCode_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getAvailableStock() != 0L) {
        setAvailableStock(other.getAvailableStock());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              productId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              countryCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              availableStock_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long productId_ ;
    /**
     * <code>int64 product_id = 1;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId_;
    }
    /**
     * <code>int64 product_id = 1;</code>
     * @param value The productId to set.
     * @return This builder for chaining.
     */
    public Builder setProductId(long value) {

      productId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 product_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      productId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object countryCode_ = "";
    /**
     * <code>string country_code = 2;</code>
     * @return The countryCode.
     */
    public java.lang.String getCountryCode() {
      java.lang.Object ref = countryCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        countryCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string country_code = 2;</code>
     * @return The bytes for countryCode.
     */
    public com.google.protobuf.ByteString
        getCountryCodeBytes() {
      java.lang.Object ref = countryCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string country_code = 2;</code>
     * @param value The countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      countryCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountryCode() {
      countryCode_ = getDefaultInstance().getCountryCode();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string country_code = 2;</code>
     * @param value The bytes for countryCode to set.
     * @return This builder for chaining.
     */
    public Builder setCountryCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      countryCode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long availableStock_ ;
    /**
     * <code>int64 available_stock = 3;</code>
     * @return The availableStock.
     */
    @java.lang.Override
    public long getAvailableStock() {
      return availableStock_;
    }
    /**
     * <code>int64 available_stock = 3;</code>
     * @param value The availableStock to set.
     * @return This builder for chaining.
     */
    public Builder setAvailableStock(long value) {

      availableStock_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 available_stock = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvailableStock() {
      bitField0_ = (bitField0_ & ~0x00000004);
      availableStock_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.stock.StockMessage)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.stock.StockMessage)
  private static final com.example.demo.stock.proto.StockMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.stock.proto.StockMessage();
  }

  public static com.example.demo.stock.proto.StockMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StockMessage>
      PARSER = new com.google.protobuf.AbstractParser<StockMessage>() {
    @java.lang.Override
    public StockMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StockMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StockMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.stock.proto.StockMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

