// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.checkout.proto;

public final class Messages {
  private Messages() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      Messages.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_checkout_RequestWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_checkout_RequestWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_checkout_ResponseWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_checkout_ResponseWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_checkout_ValidateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_checkout_ValidateOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_checkout_OrderItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_checkout_OrderItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_checkout_ValidateOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_checkout_ValidateOrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/resources/messages.proto\022\031com" +
      ".example.demo.checkout\"n\n\016RequestWrapper" +
      "\022Q\n\026validate_order_request\030\001 \001(\0132/.com.e" +
      "xample.demo.checkout.ValidateOrderReques" +
      "tH\000B\t\n\007request\"r\n\017ResponseWrapper\022S\n\027val" +
      "idate_order_response\030\001 \001(\01320.com.example" +
      ".demo.checkout.ValidateOrderResponseH\000B\n" +
      "\n\010response\"a\n\024ValidateOrderRequest\022\024\n\014co" +
      "untry_code\030\001 \001(\t\0223\n\005items\030\002 \003(\0132$.com.ex" +
      "ample.demo.checkout.OrderItem\"1\n\tOrderIt" +
      "em\022\022\n\nproduct_id\030\001 \001(\003\022\020\n\010quantity\030\002 \001(\003" +
      "\")\n\025ValidateOrderResponse\022\020\n\010is_valid\030\001 " +
      "\001(\010B&\n\037com.example.demo.checkout.protoP\001" +
      "\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_checkout_RequestWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_checkout_RequestWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_checkout_RequestWrapper_descriptor,
        new java.lang.String[] { "ValidateOrderRequest", "Request", });
    internal_static_com_example_demo_checkout_ResponseWrapper_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_demo_checkout_ResponseWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_checkout_ResponseWrapper_descriptor,
        new java.lang.String[] { "ValidateOrderResponse", "Response", });
    internal_static_com_example_demo_checkout_ValidateOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_demo_checkout_ValidateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_checkout_ValidateOrderRequest_descriptor,
        new java.lang.String[] { "CountryCode", "Items", });
    internal_static_com_example_demo_checkout_OrderItem_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_demo_checkout_OrderItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_checkout_OrderItem_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", });
    internal_static_com_example_demo_checkout_ValidateOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_demo_checkout_ValidateOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_checkout_ValidateOrderResponse_descriptor,
        new java.lang.String[] { "IsValid", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
