// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.checkout.proto;

public interface OrderItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.checkout.OrderItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>int64 quantity = 2;</code>
   * @return The quantity.
   */
  long getQuantity();
}
