// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.checkout.proto;

public interface RequestWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.checkout.RequestWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
   * @return Whether the validateOrderRequest field is set.
   */
  boolean hasValidateOrderRequest();
  /**
   * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
   * @return The validateOrderRequest.
   */
  com.example.demo.checkout.proto.ValidateOrderRequest getValidateOrderRequest();
  /**
   * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
   */
  com.example.demo.checkout.proto.ValidateOrderRequestOrBuilder getValidateOrderRequestOrBuilder();

  com.example.demo.checkout.proto.RequestWrapper.RequestCase getRequestCase();
}
