// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.checkout.proto;

/**
 * Protobuf type {@code com.example.demo.checkout.RequestWrapper}
 */
public final class RequestWrapper extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.checkout.RequestWrapper)
    RequestWrapperOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      RequestWrapper.class.getName());
  }
  // Use RequestWrapper.newBuilder() to construct.
  private RequestWrapper(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RequestWrapper() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_RequestWrapper_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_RequestWrapper_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.checkout.proto.RequestWrapper.class, com.example.demo.checkout.proto.RequestWrapper.Builder.class);
  }

  private int requestCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    VALIDATE_ORDER_REQUEST(1),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return VALIDATE_ORDER_REQUEST;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int VALIDATE_ORDER_REQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
   * @return Whether the validateOrderRequest field is set.
   */
  @java.lang.Override
  public boolean hasValidateOrderRequest() {
    return requestCase_ == 1;
  }
  /**
   * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
   * @return The validateOrderRequest.
   */
  @java.lang.Override
  public com.example.demo.checkout.proto.ValidateOrderRequest getValidateOrderRequest() {
    if (requestCase_ == 1) {
       return (com.example.demo.checkout.proto.ValidateOrderRequest) request_;
    }
    return com.example.demo.checkout.proto.ValidateOrderRequest.getDefaultInstance();
  }
  /**
   * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
   */
  @java.lang.Override
  public com.example.demo.checkout.proto.ValidateOrderRequestOrBuilder getValidateOrderRequestOrBuilder() {
    if (requestCase_ == 1) {
       return (com.example.demo.checkout.proto.ValidateOrderRequest) request_;
    }
    return com.example.demo.checkout.proto.ValidateOrderRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (com.example.demo.checkout.proto.ValidateOrderRequest) request_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.example.demo.checkout.proto.ValidateOrderRequest) request_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.checkout.proto.RequestWrapper)) {
      return super.equals(obj);
    }
    com.example.demo.checkout.proto.RequestWrapper other = (com.example.demo.checkout.proto.RequestWrapper) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getValidateOrderRequest()
            .equals(other.getValidateOrderRequest())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + VALIDATE_ORDER_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getValidateOrderRequest().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.checkout.proto.RequestWrapper parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.checkout.proto.RequestWrapper parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.checkout.proto.RequestWrapper parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.checkout.proto.RequestWrapper prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.checkout.RequestWrapper}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.checkout.RequestWrapper)
      com.example.demo.checkout.proto.RequestWrapperOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_RequestWrapper_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_RequestWrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.checkout.proto.RequestWrapper.class, com.example.demo.checkout.proto.RequestWrapper.Builder.class);
    }

    // Construct using com.example.demo.checkout.proto.RequestWrapper.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (validateOrderRequestBuilder_ != null) {
        validateOrderRequestBuilder_.clear();
      }
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_RequestWrapper_descriptor;
    }

    @java.lang.Override
    public com.example.demo.checkout.proto.RequestWrapper getDefaultInstanceForType() {
      return com.example.demo.checkout.proto.RequestWrapper.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.checkout.proto.RequestWrapper build() {
      com.example.demo.checkout.proto.RequestWrapper result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.checkout.proto.RequestWrapper buildPartial() {
      com.example.demo.checkout.proto.RequestWrapper result = new com.example.demo.checkout.proto.RequestWrapper(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.demo.checkout.proto.RequestWrapper result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.example.demo.checkout.proto.RequestWrapper result) {
      result.requestCase_ = requestCase_;
      result.request_ = this.request_;
      if (requestCase_ == 1 &&
          validateOrderRequestBuilder_ != null) {
        result.request_ = validateOrderRequestBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.checkout.proto.RequestWrapper) {
        return mergeFrom((com.example.demo.checkout.proto.RequestWrapper)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.checkout.proto.RequestWrapper other) {
      if (other == com.example.demo.checkout.proto.RequestWrapper.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case VALIDATE_ORDER_REQUEST: {
          mergeValidateOrderRequest(other.getValidateOrderRequest());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getValidateOrderRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 1;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        com.example.demo.checkout.proto.ValidateOrderRequest, com.example.demo.checkout.proto.ValidateOrderRequest.Builder, com.example.demo.checkout.proto.ValidateOrderRequestOrBuilder> validateOrderRequestBuilder_;
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     * @return Whether the validateOrderRequest field is set.
     */
    @java.lang.Override
    public boolean hasValidateOrderRequest() {
      return requestCase_ == 1;
    }
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     * @return The validateOrderRequest.
     */
    @java.lang.Override
    public com.example.demo.checkout.proto.ValidateOrderRequest getValidateOrderRequest() {
      if (validateOrderRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          return (com.example.demo.checkout.proto.ValidateOrderRequest) request_;
        }
        return com.example.demo.checkout.proto.ValidateOrderRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return validateOrderRequestBuilder_.getMessage();
        }
        return com.example.demo.checkout.proto.ValidateOrderRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     */
    public Builder setValidateOrderRequest(com.example.demo.checkout.proto.ValidateOrderRequest value) {
      if (validateOrderRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        validateOrderRequestBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     */
    public Builder setValidateOrderRequest(
        com.example.demo.checkout.proto.ValidateOrderRequest.Builder builderForValue) {
      if (validateOrderRequestBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        validateOrderRequestBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     */
    public Builder mergeValidateOrderRequest(com.example.demo.checkout.proto.ValidateOrderRequest value) {
      if (validateOrderRequestBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != com.example.demo.checkout.proto.ValidateOrderRequest.getDefaultInstance()) {
          request_ = com.example.demo.checkout.proto.ValidateOrderRequest.newBuilder((com.example.demo.checkout.proto.ValidateOrderRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          validateOrderRequestBuilder_.mergeFrom(value);
        } else {
          validateOrderRequestBuilder_.setMessage(value);
        }
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     */
    public Builder clearValidateOrderRequest() {
      if (validateOrderRequestBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        validateOrderRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     */
    public com.example.demo.checkout.proto.ValidateOrderRequest.Builder getValidateOrderRequestBuilder() {
      return getValidateOrderRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     */
    @java.lang.Override
    public com.example.demo.checkout.proto.ValidateOrderRequestOrBuilder getValidateOrderRequestOrBuilder() {
      if ((requestCase_ == 1) && (validateOrderRequestBuilder_ != null)) {
        return validateOrderRequestBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (com.example.demo.checkout.proto.ValidateOrderRequest) request_;
        }
        return com.example.demo.checkout.proto.ValidateOrderRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.example.demo.checkout.ValidateOrderRequest validate_order_request = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.example.demo.checkout.proto.ValidateOrderRequest, com.example.demo.checkout.proto.ValidateOrderRequest.Builder, com.example.demo.checkout.proto.ValidateOrderRequestOrBuilder> 
        getValidateOrderRequestFieldBuilder() {
      if (validateOrderRequestBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = com.example.demo.checkout.proto.ValidateOrderRequest.getDefaultInstance();
        }
        validateOrderRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.example.demo.checkout.proto.ValidateOrderRequest, com.example.demo.checkout.proto.ValidateOrderRequest.Builder, com.example.demo.checkout.proto.ValidateOrderRequestOrBuilder>(
                (com.example.demo.checkout.proto.ValidateOrderRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();
      return validateOrderRequestBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.checkout.RequestWrapper)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.checkout.RequestWrapper)
  private static final com.example.demo.checkout.proto.RequestWrapper DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.checkout.proto.RequestWrapper();
  }

  public static com.example.demo.checkout.proto.RequestWrapper getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestWrapper>
      PARSER = new com.google.protobuf.AbstractParser<RequestWrapper>() {
    @java.lang.Override
    public RequestWrapper parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RequestWrapper> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestWrapper> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.checkout.proto.RequestWrapper getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

