// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.checkout.proto;

public interface ResponseWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.checkout.ResponseWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.checkout.ValidateOrderResponse validate_order_response = 1;</code>
   * @return Whether the validateOrderResponse field is set.
   */
  boolean hasValidateOrderResponse();
  /**
   * <code>.com.example.demo.checkout.ValidateOrderResponse validate_order_response = 1;</code>
   * @return The validateOrderResponse.
   */
  com.example.demo.checkout.proto.ValidateOrderResponse getValidateOrderResponse();
  /**
   * <code>.com.example.demo.checkout.ValidateOrderResponse validate_order_response = 1;</code>
   */
  com.example.demo.checkout.proto.ValidateOrderResponseOrBuilder getValidateOrderResponseOrBuilder();

  com.example.demo.checkout.proto.ResponseWrapper.ResponseCase getResponseCase();
}
