// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.checkout.proto;

public interface ValidateOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.checkout.ValidateOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_valid = 1;</code>
   * @return The isValid.
   */
  boolean getIsValid();
}
