// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.checkout.proto;

/**
 * Protobuf type {@code com.example.demo.checkout.ValidateOrderResponse}
 */
public final class ValidateOrderResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.checkout.ValidateOrderResponse)
    ValidateOrderResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ValidateOrderResponse.class.getName());
  }
  // Use ValidateOrderResponse.newBuilder() to construct.
  private ValidateOrderResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ValidateOrderResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_ValidateOrderResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_ValidateOrderResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.checkout.proto.ValidateOrderResponse.class, com.example.demo.checkout.proto.ValidateOrderResponse.Builder.class);
  }

  public static final int IS_VALID_FIELD_NUMBER = 1;
  private boolean isValid_ = false;
  /**
   * <code>bool is_valid = 1;</code>
   * @return The isValid.
   */
  @java.lang.Override
  public boolean getIsValid() {
    return isValid_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isValid_ != false) {
      output.writeBool(1, isValid_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isValid_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isValid_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.checkout.proto.ValidateOrderResponse)) {
      return super.equals(obj);
    }
    com.example.demo.checkout.proto.ValidateOrderResponse other = (com.example.demo.checkout.proto.ValidateOrderResponse) obj;

    if (getIsValid()
        != other.getIsValid()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_VALID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsValid());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.checkout.proto.ValidateOrderResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.checkout.proto.ValidateOrderResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.checkout.proto.ValidateOrderResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.checkout.proto.ValidateOrderResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.checkout.ValidateOrderResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.checkout.ValidateOrderResponse)
      com.example.demo.checkout.proto.ValidateOrderResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_ValidateOrderResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_ValidateOrderResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.checkout.proto.ValidateOrderResponse.class, com.example.demo.checkout.proto.ValidateOrderResponse.Builder.class);
    }

    // Construct using com.example.demo.checkout.proto.ValidateOrderResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isValid_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.checkout.proto.Messages.internal_static_com_example_demo_checkout_ValidateOrderResponse_descriptor;
    }

    @java.lang.Override
    public com.example.demo.checkout.proto.ValidateOrderResponse getDefaultInstanceForType() {
      return com.example.demo.checkout.proto.ValidateOrderResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.checkout.proto.ValidateOrderResponse build() {
      com.example.demo.checkout.proto.ValidateOrderResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.checkout.proto.ValidateOrderResponse buildPartial() {
      com.example.demo.checkout.proto.ValidateOrderResponse result = new com.example.demo.checkout.proto.ValidateOrderResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.demo.checkout.proto.ValidateOrderResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isValid_ = isValid_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.checkout.proto.ValidateOrderResponse) {
        return mergeFrom((com.example.demo.checkout.proto.ValidateOrderResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.checkout.proto.ValidateOrderResponse other) {
      if (other == com.example.demo.checkout.proto.ValidateOrderResponse.getDefaultInstance()) return this;
      if (other.getIsValid() != false) {
        setIsValid(other.getIsValid());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isValid_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isValid_ ;
    /**
     * <code>bool is_valid = 1;</code>
     * @return The isValid.
     */
    @java.lang.Override
    public boolean getIsValid() {
      return isValid_;
    }
    /**
     * <code>bool is_valid = 1;</code>
     * @param value The isValid to set.
     * @return This builder for chaining.
     */
    public Builder setIsValid(boolean value) {

      isValid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_valid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsValid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isValid_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.checkout.ValidateOrderResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.checkout.ValidateOrderResponse)
  private static final com.example.demo.checkout.proto.ValidateOrderResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.checkout.proto.ValidateOrderResponse();
  }

  public static com.example.demo.checkout.proto.ValidateOrderResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ValidateOrderResponse>
      PARSER = new com.google.protobuf.AbstractParser<ValidateOrderResponse>() {
    @java.lang.Override
    public ValidateOrderResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ValidateOrderResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ValidateOrderResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.checkout.proto.ValidateOrderResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

