// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.checkout.proto;

public interface ValidateOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.checkout.ValidateOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string country_code = 1;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string country_code = 1;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>repeated .com.example.demo.checkout.OrderItem items = 2;</code>
   */
  java.util.List<com.example.demo.checkout.proto.OrderItem> 
      getItemsList();
  /**
   * <code>repeated .com.example.demo.checkout.OrderItem items = 2;</code>
   */
  com.example.demo.checkout.proto.OrderItem getItems(int index);
  /**
   * <code>repeated .com.example.demo.checkout.OrderItem items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .com.example.demo.checkout.OrderItem items = 2;</code>
   */
  java.util.List<? extends com.example.demo.checkout.proto.OrderItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .com.example.demo.checkout.OrderItem items = 2;</code>
   */
  com.example.demo.checkout.proto.OrderItemOrBuilder getItemsOrBuilder(
      int index);
}
