// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.catalog.proto;

public interface CreateProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.catalog.CreateProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.com.example.demo.catalog.ProductDto product = 2;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.com.example.demo.catalog.ProductDto product = 2;</code>
   * @return The product.
   */
  com.example.demo.catalog.proto.ProductDto getProduct();
  /**
   * <code>.com.example.demo.catalog.ProductDto product = 2;</code>
   */
  com.example.demo.catalog.proto.ProductDtoOrBuilder getProductOrBuilder();

  com.example.demo.catalog.proto.CreateProductResponse.ResponseCase getResponseCase();
}
