// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.catalog.proto;

public final class Messages {
  private Messages() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      Messages.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_catalog_RequestWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_catalog_RequestWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_catalog_CreateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_catalog_CreateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_catalog_ProductDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_catalog_ProductDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_catalog_ProductAttribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_catalog_ProductAttribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_catalog_ResponseWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_catalog_ResponseWrapper_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_catalog_CreateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_demo_catalog_CreateProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!src/main/resources/messages.proto\022\030com" +
      ".example.demo.catalog\"m\n\016RequestWrapper\022" +
      "P\n\026create_product_request\030\001 \001(\0132..com.ex" +
      "ample.demo.catalog.CreateProductRequestH" +
      "\000B\t\n\007request\"w\n\024CreateProductRequest\022\013\n\003" +
      "sku\030\001 \001(\t\022\022\n\nis_enabled\030\002 \001(\010\022>\n\nattribu" +
      "tes\030\003 \003(\0132*.com.example.demo.catalog.Pro" +
      "ductAttribute\"m\n\nProductDto\022\013\n\003sku\030\001 \001(\t" +
      "\022\022\n\nis_enabled\030\002 \001(\010\022>\n\nattributes\030\003 \003(\013" +
      "2*.com.example.demo.catalog.ProductAttri" +
      "bute\"\300\001\n\020ProductAttribute\022\024\n\014attribute_i" +
      "d\030\001 \001(\003\022\023\n\tint_value\030\002 \001(\005H\000\022\026\n\014bigint_v" +
      "alue\030\003 \001(\003H\000\022\027\n\rdecimal_value\030\004 \001(\001H\000\022\027\n" +
      "\rvarchar_value\030\005 \001(\tH\000\022\024\n\nblob_value\030\006 \001" +
      "(\014H\000\022\030\n\016datetime_value\030\007 \001(\tH\000B\007\n\005value\"" +
      "q\n\017ResponseWrapper\022R\n\027create_product_res" +
      "ponse\030\001 \001(\0132/.com.example.demo.catalog.C" +
      "reateProductResponseH\000B\n\n\010response\"h\n\025Cr" +
      "eateProductResponse\022\n\n\002id\030\001 \001(\003\0227\n\007produ" +
      "ct\030\002 \001(\0132$.com.example.demo.catalog.Prod" +
      "uctDtoH\000B\n\n\010responseB%\n\036com.example.demo" +
      ".catalog.protoP\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_demo_catalog_RequestWrapper_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_catalog_RequestWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_catalog_RequestWrapper_descriptor,
        new java.lang.String[] { "CreateProductRequest", "Request", });
    internal_static_com_example_demo_catalog_CreateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_demo_catalog_CreateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_catalog_CreateProductRequest_descriptor,
        new java.lang.String[] { "Sku", "IsEnabled", "Attributes", });
    internal_static_com_example_demo_catalog_ProductDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_demo_catalog_ProductDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_catalog_ProductDto_descriptor,
        new java.lang.String[] { "Sku", "IsEnabled", "Attributes", });
    internal_static_com_example_demo_catalog_ProductAttribute_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_demo_catalog_ProductAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_catalog_ProductAttribute_descriptor,
        new java.lang.String[] { "AttributeId", "IntValue", "BigintValue", "DecimalValue", "VarcharValue", "BlobValue", "DatetimeValue", "Value", });
    internal_static_com_example_demo_catalog_ResponseWrapper_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_demo_catalog_ResponseWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_catalog_ResponseWrapper_descriptor,
        new java.lang.String[] { "CreateProductResponse", "Response", });
    internal_static_com_example_demo_catalog_CreateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_demo_catalog_CreateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_demo_catalog_CreateProductResponse_descriptor,
        new java.lang.String[] { "Id", "Product", "Response", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
