// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.catalog.proto;

/**
 * Protobuf type {@code com.example.demo.catalog.ProductDto}
 */
public final class ProductDto extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.example.demo.catalog.ProductDto)
    ProductDtoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      ProductDto.class.getName());
  }
  // Use ProductDto.newBuilder() to construct.
  private ProductDto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ProductDto() {
    sku_ = "";
    attributes_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.catalog.proto.Messages.internal_static_com_example_demo_catalog_ProductDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.catalog.proto.Messages.internal_static_com_example_demo_catalog_ProductDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.catalog.proto.ProductDto.class, com.example.demo.catalog.proto.ProductDto.Builder.class);
  }

  public static final int SKU_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sku_ = "";
  /**
   * <code>string sku = 1;</code>
   * @return The sku.
   */
  @java.lang.Override
  public java.lang.String getSku() {
    java.lang.Object ref = sku_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sku_ = s;
      return s;
    }
  }
  /**
   * <code>string sku = 1;</code>
   * @return The bytes for sku.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSkuBytes() {
    java.lang.Object ref = sku_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sku_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_ENABLED_FIELD_NUMBER = 2;
  private boolean isEnabled_ = false;
  /**
   * <code>bool is_enabled = 2;</code>
   * @return The isEnabled.
   */
  @java.lang.Override
  public boolean getIsEnabled() {
    return isEnabled_;
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.example.demo.catalog.proto.ProductAttribute> attributes_;
  /**
   * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.demo.catalog.proto.ProductAttribute> getAttributesList() {
    return attributes_;
  }
  /**
   * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.demo.catalog.proto.ProductAttributeOrBuilder> 
      getAttributesOrBuilderList() {
    return attributes_;
  }
  /**
   * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
   */
  @java.lang.Override
  public int getAttributesCount() {
    return attributes_.size();
  }
  /**
   * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
   */
  @java.lang.Override
  public com.example.demo.catalog.proto.ProductAttribute getAttributes(int index) {
    return attributes_.get(index);
  }
  /**
   * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
   */
  @java.lang.Override
  public com.example.demo.catalog.proto.ProductAttributeOrBuilder getAttributesOrBuilder(
      int index) {
    return attributes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sku_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sku_);
    }
    if (isEnabled_ != false) {
      output.writeBool(2, isEnabled_);
    }
    for (int i = 0; i < attributes_.size(); i++) {
      output.writeMessage(3, attributes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sku_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sku_);
    }
    if (isEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isEnabled_);
    }
    for (int i = 0; i < attributes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, attributes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.catalog.proto.ProductDto)) {
      return super.equals(obj);
    }
    com.example.demo.catalog.proto.ProductDto other = (com.example.demo.catalog.proto.ProductDto) obj;

    if (!getSku()
        .equals(other.getSku())) return false;
    if (getIsEnabled()
        != other.getIsEnabled()) return false;
    if (!getAttributesList()
        .equals(other.getAttributesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKU_FIELD_NUMBER;
    hash = (53 * hash) + getSku().hashCode();
    hash = (37 * hash) + IS_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsEnabled());
    if (getAttributesCount() > 0) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.catalog.proto.ProductDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.demo.catalog.proto.ProductDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.demo.catalog.proto.ProductDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.catalog.proto.ProductDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.catalog.proto.ProductDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.demo.catalog.ProductDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.demo.catalog.ProductDto)
      com.example.demo.catalog.proto.ProductDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.catalog.proto.Messages.internal_static_com_example_demo_catalog_ProductDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.catalog.proto.Messages.internal_static_com_example_demo_catalog_ProductDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.catalog.proto.ProductDto.class, com.example.demo.catalog.proto.ProductDto.Builder.class);
    }

    // Construct using com.example.demo.catalog.proto.ProductDto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sku_ = "";
      isEnabled_ = false;
      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
      } else {
        attributes_ = null;
        attributesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.catalog.proto.Messages.internal_static_com_example_demo_catalog_ProductDto_descriptor;
    }

    @java.lang.Override
    public com.example.demo.catalog.proto.ProductDto getDefaultInstanceForType() {
      return com.example.demo.catalog.proto.ProductDto.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.catalog.proto.ProductDto build() {
      com.example.demo.catalog.proto.ProductDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.catalog.proto.ProductDto buildPartial() {
      com.example.demo.catalog.proto.ProductDto result = new com.example.demo.catalog.proto.ProductDto(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.demo.catalog.proto.ProductDto result) {
      if (attributesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          attributes_ = java.util.Collections.unmodifiableList(attributes_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.attributes_ = attributes_;
      } else {
        result.attributes_ = attributesBuilder_.build();
      }
    }

    private void buildPartial0(com.example.demo.catalog.proto.ProductDto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sku_ = sku_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isEnabled_ = isEnabled_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.catalog.proto.ProductDto) {
        return mergeFrom((com.example.demo.catalog.proto.ProductDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.catalog.proto.ProductDto other) {
      if (other == com.example.demo.catalog.proto.ProductDto.getDefaultInstance()) return this;
      if (!other.getSku().isEmpty()) {
        sku_ = other.sku_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIsEnabled() != false) {
        setIsEnabled(other.getIsEnabled());
      }
      if (attributesBuilder_ == null) {
        if (!other.attributes_.isEmpty()) {
          if (attributes_.isEmpty()) {
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAttributesIsMutable();
            attributes_.addAll(other.attributes_);
          }
          onChanged();
        }
      } else {
        if (!other.attributes_.isEmpty()) {
          if (attributesBuilder_.isEmpty()) {
            attributesBuilder_.dispose();
            attributesBuilder_ = null;
            attributes_ = other.attributes_;
            bitField0_ = (bitField0_ & ~0x00000004);
            attributesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getAttributesFieldBuilder() : null;
          } else {
            attributesBuilder_.addAllMessages(other.attributes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sku_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isEnabled_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              com.example.demo.catalog.proto.ProductAttribute m =
                  input.readMessage(
                      com.example.demo.catalog.proto.ProductAttribute.parser(),
                      extensionRegistry);
              if (attributesBuilder_ == null) {
                ensureAttributesIsMutable();
                attributes_.add(m);
              } else {
                attributesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sku_ = "";
    /**
     * <code>string sku = 1;</code>
     * @return The sku.
     */
    public java.lang.String getSku() {
      java.lang.Object ref = sku_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sku_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sku = 1;</code>
     * @return The bytes for sku.
     */
    public com.google.protobuf.ByteString
        getSkuBytes() {
      java.lang.Object ref = sku_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sku_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sku = 1;</code>
     * @param value The sku to set.
     * @return This builder for chaining.
     */
    public Builder setSku(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sku_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sku = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSku() {
      sku_ = getDefaultInstance().getSku();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sku = 1;</code>
     * @param value The bytes for sku to set.
     * @return This builder for chaining.
     */
    public Builder setSkuBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sku_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean isEnabled_ ;
    /**
     * <code>bool is_enabled = 2;</code>
     * @return The isEnabled.
     */
    @java.lang.Override
    public boolean getIsEnabled() {
      return isEnabled_;
    }
    /**
     * <code>bool is_enabled = 2;</code>
     * @param value The isEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setIsEnabled(boolean value) {

      isEnabled_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_enabled = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsEnabled() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isEnabled_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.example.demo.catalog.proto.ProductAttribute> attributes_ =
      java.util.Collections.emptyList();
    private void ensureAttributesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        attributes_ = new java.util.ArrayList<com.example.demo.catalog.proto.ProductAttribute>(attributes_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.demo.catalog.proto.ProductAttribute, com.example.demo.catalog.proto.ProductAttribute.Builder, com.example.demo.catalog.proto.ProductAttributeOrBuilder> attributesBuilder_;

    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public java.util.List<com.example.demo.catalog.proto.ProductAttribute> getAttributesList() {
      if (attributesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attributes_);
      } else {
        return attributesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public int getAttributesCount() {
      if (attributesBuilder_ == null) {
        return attributes_.size();
      } else {
        return attributesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public com.example.demo.catalog.proto.ProductAttribute getAttributes(int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);
      } else {
        return attributesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder setAttributes(
        int index, com.example.demo.catalog.proto.ProductAttribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.set(index, value);
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder setAttributes(
        int index, com.example.demo.catalog.proto.ProductAttribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder addAttributes(com.example.demo.catalog.proto.ProductAttribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder addAttributes(
        int index, com.example.demo.catalog.proto.ProductAttribute value) {
      if (attributesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributesIsMutable();
        attributes_.add(index, value);
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder addAttributes(
        com.example.demo.catalog.proto.ProductAttribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder addAttributes(
        int index, com.example.demo.catalog.proto.ProductAttribute.Builder builderForValue) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder addAllAttributes(
        java.lang.Iterable<? extends com.example.demo.catalog.proto.ProductAttribute> values) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attributes_);
        onChanged();
      } else {
        attributesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder clearAttributes() {
      if (attributesBuilder_ == null) {
        attributes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        attributesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public Builder removeAttributes(int index) {
      if (attributesBuilder_ == null) {
        ensureAttributesIsMutable();
        attributes_.remove(index);
        onChanged();
      } else {
        attributesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public com.example.demo.catalog.proto.ProductAttribute.Builder getAttributesBuilder(
        int index) {
      return getAttributesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public com.example.demo.catalog.proto.ProductAttributeOrBuilder getAttributesOrBuilder(
        int index) {
      if (attributesBuilder_ == null) {
        return attributes_.get(index);  } else {
        return attributesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public java.util.List<? extends com.example.demo.catalog.proto.ProductAttributeOrBuilder> 
         getAttributesOrBuilderList() {
      if (attributesBuilder_ != null) {
        return attributesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attributes_);
      }
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public com.example.demo.catalog.proto.ProductAttribute.Builder addAttributesBuilder() {
      return getAttributesFieldBuilder().addBuilder(
          com.example.demo.catalog.proto.ProductAttribute.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public com.example.demo.catalog.proto.ProductAttribute.Builder addAttributesBuilder(
        int index) {
      return getAttributesFieldBuilder().addBuilder(
          index, com.example.demo.catalog.proto.ProductAttribute.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.demo.catalog.ProductAttribute attributes = 3;</code>
     */
    public java.util.List<com.example.demo.catalog.proto.ProductAttribute.Builder> 
         getAttributesBuilderList() {
      return getAttributesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.example.demo.catalog.proto.ProductAttribute, com.example.demo.catalog.proto.ProductAttribute.Builder, com.example.demo.catalog.proto.ProductAttributeOrBuilder> 
        getAttributesFieldBuilder() {
      if (attributesBuilder_ == null) {
        attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.example.demo.catalog.proto.ProductAttribute, com.example.demo.catalog.proto.ProductAttribute.Builder, com.example.demo.catalog.proto.ProductAttributeOrBuilder>(
                attributes_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        attributes_ = null;
      }
      return attributesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.example.demo.catalog.ProductDto)
  }

  // @@protoc_insertion_point(class_scope:com.example.demo.catalog.ProductDto)
  private static final com.example.demo.catalog.proto.ProductDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.catalog.proto.ProductDto();
  }

  public static com.example.demo.catalog.proto.ProductDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductDto>
      PARSER = new com.google.protobuf.AbstractParser<ProductDto>() {
    @java.lang.Override
    public ProductDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ProductDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.catalog.proto.ProductDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

