// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/resources/messages.proto
// Protobuf Java Version: 4.27.3

package com.example.demo.catalog.proto;

public interface ResponseWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.demo.catalog.ResponseWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.demo.catalog.CreateProductResponse create_product_response = 1;</code>
   * @return Whether the createProductResponse field is set.
   */
  boolean hasCreateProductResponse();
  /**
   * <code>.com.example.demo.catalog.CreateProductResponse create_product_response = 1;</code>
   * @return The createProductResponse.
   */
  com.example.demo.catalog.proto.CreateProductResponse getCreateProductResponse();
  /**
   * <code>.com.example.demo.catalog.CreateProductResponse create_product_response = 1;</code>
   */
  com.example.demo.catalog.proto.CreateProductResponseOrBuilder getCreateProductResponseOrBuilder();

  com.example.demo.catalog.proto.ResponseWrapper.ResponseCase getResponseCase();
}
